### ISSUE TITLE
Error detected while cargo build.

### ISSUE THREAD

**Issue by callmedevops** [Razican/Rust-web-template#15]
Compiling web_template v0.1.0 (/home/dell/Downloads/Rust-web-template-master)
error[E0432]: unresolved import `super::super::schema::oauth_apps`
 --> src/db/models/oauth.rs:6:5
  |
6 | use super::super::schema::oauth_apps;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `oauth_apps` in `db::schema`

error[E0432]: unresolved import `rocket_contrib::Template`
  --> src/compress.rs:10:5
   |
10 | use rocket_contrib::Template;
   |     ^^^^^^^^^^^^^^^^--------
   |     |               |
   |     |               help: a similar name exists in the module: `templates`
   |     no `Template` in the root

error[E0432]: unresolved import `rocket_contrib::Json`
   --> src/compress.rs:109:13
    |
109 |         use rocket_contrib::Json;
    |             ^^^^^^^^^^^^^^^^----
    |             |               |
    |             |               help: a similar name exists in the module: `json`
    |             no `Json` in the root

error[E0432]: unresolved import `rocket_contrib::Json`
 --> src/api/v1/oauth.rs:5:5
  |
5 | use rocket_contrib::Json;
  |     ^^^^^^^^^^^^^^^^----
  |     |               |
  |     |               help: a similar name exists in the module: `json`
  |     no `Json` in the root

error[E0432]: unresolved import `rocket_contrib::Template`
  --> src/lib.rs:45:5
   |
45 | use rocket_contrib::Template;
   |     ^^^^^^^^^^^^^^^^--------
   |     |               |
   |     |               help: a similar name exists in the module: `templates`
   |     no `Template` in the root

error: cannot find attribute `post` in this scope
   --> src/api/v1/oauth.rs:129:3
    |
129 | #[post("/refresh_token", data = "<credentials>")]
    |   ^^^^

error: cannot find attribute `get` in this scope
   --> src/api/v1/oauth.rs:145:3
    |
145 | #[get("/access_token")]
    |   ^^^

error: cannot find attribute `get` in this scope
  --> src/lib.rs:50:3
   |
50 | #[get("/")]
   |   ^^^

error: cannot find attribute `get` in this scope
  --> src/lib.rs:84:3
   |
84 | #[get("/img/<file..>")]
   |   ^^^

error: cannot find attribute `get` in this scope
  --> src/lib.rs:90:3
   |
90 | #[get("/favicon.ico")]
   |   ^^^

error: cannot find attribute `get` in this scope
  --> src/lib.rs:96:3
   |
96 | #[get("/fav/browserconfig.xml")]
   |   ^^^

error: cannot find attribute `get` in this scope
   --> src/lib.rs:102:3
    |
102 | #[get("/fav/manifest.json")]
    |   ^^^

error: cannot find attribute `get` in this scope
   --> src/lib.rs:108:3
    |
108 | #[get("/fav/<file..>", rank = 2)]
    |   ^^^

error: cannot find attribute `get` in this scope
   --> src/lib.rs:114:3
    |
114 | #[get("/css/<file..>")]
    |   ^^^

error: cannot find attribute `get` in this scope
   --> src/lib.rs:123:3
    |
123 | #[get("/js/<file..>")]
    |   ^^^

error[E0412]: cannot find type `AccessTokenResponse` in this scope
  --> src/api/v1/oauth.rs:18:19
   |
18 |     access_token: AccessTokenResponse,
   |                   ^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `hex_str` in this scope
  --> src/api/v1/oauth.rs:24:30
   |
24 |     #[serde(serialize_with = "hex_str")]
   |                              ^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `Scope` in this scope
   --> src/api/v1/oauth.rs:140:16
    |
139 | pub struct AccessToken {
    |                       - help: you might be missing a type parameter: `<Scope>`
140 |     scope: Vec<Scope>,
    |                ^^^^^ not found in this scope

warning: use of deprecated item 'diesel_infer_schema': Diesel CLI can be configured to automatically run `print-schema` after running migrations. See diesel.rs/guides/configuring-diesel-cli for details.
  --> src/lib.rs:30:1
   |
30 | extern crate diesel_infer_schema;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

error[E0283]: type annotations needed for `chrono::DateTime<Tz>`
  --> src/api/v1/oauth.rs:62:29
   |
62 |             let date_time = DateTime::from_utc(NaiveDateTime::from_timestamp(timestamp, 0), Utc);
   |                 ---------   ^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `Tz`
   |                 |
   |                 consider giving `date_time` the explicit type `chrono::DateTime<Tz>`, where the type parameter `Tz` is specified
   |
   = note: cannot satisfy `_: chrono::TimeZone`
   = note: required by `chrono::DateTime::<Tz>::from_utc`

error: aborting due to 19 previous errors; 1 warning emitted

Some errors have detailed explanations: E0283, E0412, E0425, E0432.
For more information about an error, try `rustc --explain E0283`.
error: could not compile `web_template`.

To learn more, run the command again with --verbose

**Comment by Razican** [comment]
Hi @surajsah2053 note that this repository is very outdated. I might try to fix this issue, but there are far more up to date templates out there :)

**Comment by callmedevops** [comment]
Thank you
